### ISSUE TITLE
~/.md2key

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/md2key#10]
It'd be good to have `~/.md2key` for configuration.

```yaml
code:
  font_family: Monaco
  font_size: 26

custom_thems:
  - name: Theme1
    bold_color: [0, 255, 255]
    italic_color: [0, 255, 0]
    default_template: master1
  - name: Theme2
    font_family: Monaco
```
